"""Tool Context data models.

ToolContext represents temporary context generated by an Athena native tool
(e.g., /system, /web, /document). It exists only for the current request
and is NOT persisted to any memory system.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class ToolContext:
    """Temporary context generated by an Athena native tool.

    This context is injected into the prompt for a single request.
    It is NOT stored in Working Memory, Semantic Memory, or Chat History.

    Attributes:
        tool_name: Identifier for the tool (e.g., "system", "web", "document").
        content: The rendered context string to be injected into the prompt.
        prompt: The user's prompt or query for this tool instance.
        priority: Priority level for context budgeting (default 70 for tools).
        learning_visible: Whether this context is visible to the Knowledge Extractor.
        metadata: Additional tool-specific information.
    """
    tool_name: str = ""
    content: str = ""
    prompt: str = ""
    priority: int = 70
    learning_visible: bool = True
    metadata: dict = field(default_factory=dict)