"""
Athena Thought Model

Defines the Thought dataclass, which represents the complete internal state
of processing one user request. Every future subsystem (memory, reasoning,
planning, tools, knowledge, reflection) will operate on this object.
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

from athena.planner.models import PlannerDecision
from athena.tools.models import ToolContext


@dataclass
class Thought:
    """
    Represents the complete internal state of processing one user request.

    This is the central cognitive object in Athena's architecture. Every subsystem
    reads from and writes to this object during request processing.

    Fields:
        id: Unique identifier for this thought.
        created_at: Timestamp when this thought was created.
        user_input: The raw input from the user.
        intent: Parsed/intended meaning of the input.
        confidence: Confidence level in intent understanding (0-1).
        context: Current contextual information.
        memories: Related memories retrieved during processing.
        knowledge: Knowledge data accessed during processing.
        plan: Execution plan generated by the reasoning engine.
        tool_requests: Requests for external tools/services.
        tool_results: Results from executed tools.
        tool_context: Temporary context injected by a native tool (e.g., /system).
        planner_decision: Decision produced by the Tool Planner.
        response: Final response built by the thought pipeline.
        reflection: Self-evaluation of the processing outcome.
        metadata: Additional processing metadata.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created_at: datetime = field(default_factory=datetime.utcnow)
    user_input: str = ""
    intent: Any = None
    confidence: float = 0.0
    context: Any = None
    memories: list = field(default_factory=list)
    knowledge: Any = None
    plan: list = field(default_factory=list)
    tool_requests: list = field(default_factory=list)
    tool_results: list = field(default_factory=list)
    tool_context: Optional[ToolContext] = None          # Primary (first) tool context, for compatibility
    tool_contexts: list = field(default_factory=list)   # All tool contexts when tools are chained
    planner_decision: Optional[PlannerDecision] = None   # Primary (first) decision, for compatibility
    planner_decisions: list = field(default_factory=list)  # All decisions when tools are chained
    reasoning_package: Any = None
    learning_package: Any = None
    response: Any = None
    reflection: Any = None
    metadata: dict = field(default_factory=dict)
    trace: dict = field(default_factory=dict)
    history: list = field(default_factory=list)
    candidates: list = field(default_factory=list)

    def set_user_input(self, user_input: str):
        """Set the user input for this thought."""
        self.user_input = user_input

    def get_response(self) -> Any:
        """Get the final response if available, else None."""
        return self.response

    def set_response(self, response: Any):
        """Set the final response."""
        self.response = response